apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  labels:
    app: registry
  namespace: registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:3
          env:
            - name: OTEL_TRACES_EXPORTER
              value: none
            - name: REGISTRY_LOG_LEVEL
              value: info
          ports:
            - containerPort: 5000

