apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
