apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: postgres
spec:
  instances: 2 
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-minimal-bookworm
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "750m"