apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    -  repoURL: https://charts.longhorn.io/
       chart: longhorn
      targetRevision: v1.9.0 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
    - repoURL: https://github.com/tk-hap/homelab.git
      path: apps/longhorn/namespace.yaml
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
