- name: Setup dev tools
  hosts: localhost
  connection: local

  tasks:
    - name: Update APT packages 
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade to latest APT packages
      become: yes
      apt:
        upgrade: yes

    - name: Install packages
      become: yes
      apt:
        pkg:
          - curl
          - tmux
          - tldr
          - htop
          - vim
